### PR TITLE
Fixes #117 - Moved BasicVariableTestSuite to run after ResourceTimeSourceTestSuite & added timeout

### LINKED ISSUE #117: Bug: Strange bug in "Time Sources: Expiry Frames" in ResourceTimeSourceTestSuite causes it to get stuck until expiring, only when running after BasicVariableTestSuite
### Description

Currently when running the Test Framework, it will get stuck on the fact `"Time Sources: Expiry Frames"` in `ResourceTimeSourceTestSuite` for a minute until it expires, causing the framework to take significantly longer to run than it would otherwise.

image

This seems to only occur when `ResourceTimeSourceTestSuite` is run after `BasicVariableTestSuite`, as when `BasicVariableTestSuite` is commented out or moved after, the fact will run and pass as normal. 

### Cause of the Issue

The exceptions listed in the test results after the test expires suggest the reason it gets stuck is due to the `generateRandomConfigWithExpiryFrame()` constructor function not generating a valid struct to be inputted into `time_source_create` on line 379 of `ResourceTimeSourceTestSuite`, however as far as I can tell there are no errors with the code in `generateRandomConfigWithExpiryFrame()` that should cause this.

image

image

Where it gets even weirder, is its connection to `BasicVariableTestSuite`. Specifically, it seems to be the `"builtin_constant_varnames_test"` fact within `BasicVariableTestSuite` that causes this issue - commenting out a large amount of the entries in the `input` struct within it will stop the issue from happening, despite this seemingly having no connection to `ResourceTimeSourceTestSuite`. Additionally, commenting out any set of entries within the `input` struct seems to work, as long as it's around over 108 of them, suggesting it's linked somehow to the size of the struct, rather than it's contents:

image
image
(^ Had to comment out all the lines in and between these screenshots for it to work)

I haven't been able to pinpoint the exact cause or reproduce the issue outside of the Test Framework yet, but it seems more likely an actual gamemaker bug, rather than a bug with the framework. The main reason it was reported here is because a temporary fix should be put in place to stop the large run time increase this causes.

### Expected Change

For now, moving `BasicVariableTestSuite` after `ResourceTimeSourceTestSuite` should temporarily solve the issue - but this bug should be looked into further to figure out exactly what's causing it.

### Script Name

BasicVariableTestSuite/ResourceTimeSourceTestSuite

### Fact/Assert Name

"Time Sources: Expiry Frames"/"builtin_constant_varnames_test"

### How reliably does this issue happen?

Always

### PR DESCRIPTION
**Pull request by Indibulous**
Moved BasicVariableTestSuite to run after ResourceTimeSourceTestSuite in objRunner.

Also added a 3000 millisecond timeout to "Time Sources: Expiry Frames" in ResourceTimeSourceTestSuite.

### CODE REVIEW

**Review by AdamBorek — APPROVED** [review]
👍

**Comment by DiasFranciscoA** [comment]
> Moved BasicVariableTestSuite to run after ResourceTimeSourceTestSuite in objRunner.

Why was this moved? Was there a problem with it?

**Comment by Indibulous** [comment]
@DiasFranciscoA as described in #117 , still unsure of the exact cause, but the TestAsync "Time Sources: Expiry Frames" in ResourceTimeSourceTestSuite seems to have errors that only occur when run after BasicVariableTestSuite. This causes the framework to get stuck on it for a minute until it expires, additionally flooding the output log with errors once finishing, which is not ideal - so this is just a temporary fix until the bug is properly figured out. I've put more info about it in the issue.

**Comment by DiasFranciscoA** [comment]
@Indibulous there are some tests in the BasicVariableTestSuite that deal with builtin named struct variables:

image

can you please check if commenting these solved the issue? Basically commenting the:

```
other: value,
all: value,
noone: value,
global: value,
undefined: value,
...
true: value,
false: value,
pi: value,
NaN: value,
infinity: value,
```

I suspect it might be one of these.... probably good to track down which one 🤔

**Review by DiasFranciscoA — APPROVED** [review]

**Pull request merged**
